### ISSUE TITLE
Options to change dictionary don't exist; Incorrect spelling isn't marked

### ISSUE THREAD

**Issue by Okramto** [JohnathonKoster/brackets-spellcheck#1]
Title sums everything up well enough.

[Have a screenshot.](https://anonm.gr/c853.png)

Here's some system info:

```
OS: Manjaro Linux 16.06 (amd64)
Kernel: 4.5.7
Brackets version: 1.7
```

**Comment by JohnathonKoster** [comment]
Hi there,

Looks like you are missing the dictionaries extension that is required:

https://github.com/JohnathonKoster/brackets-spellcheck-dictionaries

This is done so that updates to the spell checker plugin would not require users to re-download all of the dictionaries.

It is important that the dictionaries are stored in a directory named `stillat.linguistics-dictionary` within Bracket's user extensions folder. I'll make sure to make a note that the directory name is required.

**Comment by JohnathonKoster** [comment]
The fix is now available. Check the installation notes at https://github.com/JohnathonKoster/brackets-spellcheck-dictionaries.

**Comment by Okramto** [comment]
Changing the name of the directory has had no effect. Does the spellcheck extension require a specific name as well?

I've noticed now that Brackets is reporting errors, and your assumption was correct. It is not finding the dictionaries. Here are the specific errors I'm getting:

```
Can't load the affix data for en_US NotFound ErrorNotification.js:125
Can't load the dictionary data for en_US NotFound ErrorNotification.js:125
Can't load the affix data for en_US NotFound ErrorNotification.js:125
Can't load the dictionary data for en_US NotFound ErrorNotification.js:125
```

My extensions directory looks like this:

```
user
- brackets-emmet
- brackets-spellcheck-master
- stillat.linguistics-dictionary
```

Disabling emmet has no effect. I've tried renaming `brackets-spellcheck-master` to both `brackets-spellcheck` and `spellcheck` without any change.

**Comment by JohnathonKoster** [comment]
Emmet, or other third-party extensions, shouldn't have an effect on the spellchecking plugin itself. Your directory structure also looks good.

I've updated the spellchecker code to fix this issue, so you will have to grab the new version from GitHub and install it into the spellchecker plugin directory (not the dictionary directory). Here is the relevant commit: https://github.com/JohnathonKoster/brackets-spellcheck/commit/cc8a8ca2874c90998e0f11d89358a4e1d7db07c9.

Let me know if this helps

**Comment by Okramto** [comment]
Yep, issue solved.

Thanks for this extension. You've made Brackets a viable editor.
