### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by Jaknil** [JohnathonKoster/brackets-spellcheck#2]
I can not figure out how to install these. If both directories are placed in the same folder (Brackets\extensions\user) then the main.js files conflict. No matter in which combination I try to add them I get Extension errors in the Brackets Extension manager. Running windows 10.

**Comment by JohnathonKoster** [comment]
Hi there!

You will have two directories related to this extension inside your user extensions directory:

```
brackets-spellcheck/
stillat.linguistics-dictionary/
```

For the dictionaries (`stillat.linguistics-dictionary/` directory), download the files here: [https://github.com/JohnathonKoster/brackets-spellcheck-dictionaries](https://github.com/JohnathonKoster/brackets-spellcheck-dictionaries) and copy and paste them into your extensions directory (something like `Brackets/extensions/user/stillat.linguistics-dictionary/`). The directory name is important for this one.

For the `brackets-spellcheck/` directory download the files here [https://github.com/JohnathonKoster/brackets-spellcheck](https://github.com/JohnathonKoster/brackets-spellcheck) and place them in that directory.

That should be all you need to do to get things up and running :)
