### ISSUE TITLE
Getting Spellcheck working

### ISSUE THREAD

**Issue by sciman** [JohnathonKoster/brackets-spellcheck#3]
Sorry to bother. Newbie here with limited skills, struggling to use this beautiful program for writing. But I need red underscores to flag typing/spelling errors.  

I'm working at home on an iMac with OS X High Sierra. 

I have installed Brackets 1.11 and a variety of extensions, including the two you mentioned.. as well as the spell-checking one. I can see under edit commands for spelling in a variety of languages. This seems to work on a simple text file. With a brown background, I get misspelled words in a harsh yellow that's hard to see. If I edit to correct and rerun, error yellow bands disappear. 

But I also have your two extensions installed, and they would seem to work differently and allow red lines for me without having to manually trigger. That's what I want. But after installing, I don't get the dictionary selection at lower right, though I have a field there called "proofing options", though when I toggle to select "  enable/disable the spell checker, nothing seems to happen. If I disable the 'other' spell-check, the optional languages disappear, but no dictionary choices appear lower right. 

Any tips would be deeply appreciated. 

Steve Iman, retired prof
sciman@cpp.edu

**Comment by JohnathonKoster** [comment]
@sciman 

Not a bother at all! This is a question I get asked quite a bit through different communication channels; I decided to write an official write-up on the blog:

https://stillat.com/blog/2017/10/31/installing-linguistics-for-adobe-brackets

Just work through that and you should be good to go; if you continue to have troubles just get in touch through the site or GitHub.

Thanks for taking the time to inquire very politely  :)

- John

**Comment by sciman** [comment]
Thanks John. I’ll do my best and much appreciate the help. 

Steve Iman
