### ISSUE TITLE
Adding words to the dictionary?

### ISSUE THREAD

**Issue by Andy-ABTec** [JohnathonKoster/brackets-spellcheck#4]
Hi, sorry to trouble you...
First I'd like to say how much I like your spell checker, it's doing a good job with my .md documentation. for an ongoing github project. I really like how unobtrusive it is.

I'm sure you've been asked this many times before (and apologies, I couldn't find an answer), but is there a way of adding words to the dictionary - I realize it can't be done through the UI at the moment?

I've just stumbled on "configurability" which is indicated as being spelt incorrectly.

Many thanks,

Andy B.

**Comment by JohnathonKoster** [comment]
No worries at all.

I have been in the process of slowly updating this extension to much more user friendly; this is a feature that is on the list to be implemented completely :)

If you'd like, you can remove your current extension install and search "Alice - Spelling Dictionary" in  the Bracket Extension Manager (where all new updates will start coming). The new install process automatically configures the dictionaries for you, but also has an "Ignore Once" and "Ignore All" feature you can use while you wait for custom dictionary support!

Thanks!

John

**Comment by Andy-ABTec** [comment]
Great stuff, I'll keep a weather eye open...
